server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: "33448023."
  redis:
    host: localhost
    port: 6379
#    password: 123456
    database: 0
  cache:
    redis:
      time-to-live: 1800000 # 设置缓存过期时间
#-------------------------------------------------
#  shardingsphere:
#    datasource:
#      names:
#        master,slave
#      #主数据源
#      master:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://"服务器1网址"alhost/reggie?characterEncoding=utf-8
#        username: root
#        password: root
#      # 从数据源
#      slave:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://"服务器2网址"/reggie?characterEncoding=utf-8
#        username: root
#        password: root
#    #读写分离配置
#    masterslave:
#      # 轮询
#      load-balance-algorithm-type: round_robin
#      # 最终数据源名称
#      name: dataSource
#      # 主数据库名称
#      master-data-source-name: master
#      # 从数据库名称列表，多个逗号分割
#      slave-data-source-names: slave
#    props:
#      sql:
#        show: true # 开启SQL显示，默认为false
#  main:
#    allow-bean-definition-overriding: true
#
#  redis:
#    host: localhost
#    port: 6379
#    #    password: 123456
#    database: 0
#  cache:
#    redis:
#      time-to-live: 1800000 # 设置缓存过期时间
#-----------------------------------------------------
mybatis-plus:
  configuration:
    # 在映射实体或者属性的时候，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: D:\img\
